In [ ]:
import numpy as np

# One dimensional array

In [ ]:
a = [1,2,3,4,5]
b = np.array(a)
b

array([1, 2, 3, 4, 5])

In [ ]:
a = []
size  = int(input("Enter size:"))
for i in range(size):
    val = int(input("Enter number:"))
    a.append(val)

print(a)
b = np.array(a)
b

Enter size:5
Enter number:1
Enter number:2
Enter number:3
Enter number:4
Enter number:5
[1, 2, 3, 4, 5]


array([1, 2, 3, 4, 5])

# Two dimensional array

In [ ]:
a  = [[1,2,3] , [4,5,6] , [7,8,9]]
b = np.array(a)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# How to check size and diemnsion of an array  ?

In [ ]:
a  = [[1,2,3] , [4,5,6] , [7,8,9]]
b = np.array(a)
b


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
print("Total Dimensions :" , b.ndim)
print("Shape of an array :" , b.shape)

Total Dimensions : 2
Shape of an array : (3, 3)


# Numpy Functions ==>



# 1 . Zeros ==> This function create an array (either one dimensional or multi dimensional) and fill all the values with zeros .

In [ ]:
import numpy as np
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [ ]:
b = np.zeros((2,3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
b.ndim

2

In [ ]:
a.ndim

1

# 2 . Ones ==> This function creats an array (either one dimensional or multi dimensional) and fill all the values with one .

In [ ]:
import  numpy as np
a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [ ]:
b = np.ones((2,3))
b

array([[1., 1., 1.],
       [1., 1., 1.]])

# 3 . eye ==> This function creats an array with all the digonal elements as 1 and rest are 0(In square matrix). In non-square matrix the value are sstill one for digonal (upto which it can draw digonal ) and rest are zero .

In [ ]:
import numpy as np
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
b = np.eye(3,4)
b

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

# 4 . diag ==> This function creats a two dimensional array with all the digonal elements as the given value and rest are zero .

In [ ]:
import numpy as np
a = np.diag([1,4,8,9])
a

array([[1, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 8, 0],
       [0, 0, 0, 9]])

# 5 . randint ==> This  function is used to generate a random number between a given range .

# syntax == randint(min_value , max_value , total_numbers)

In [ ]:
import numpy as np
a = np.random.randint(1,10,3)
a

array([6, 9, 4])

# 6 . rand() ==> This function is used to generate a random number between 0 to 1 .

# syntax == rand(numberof values)

In [ ]:
import numpy as np

a = np.random.rand(5)
a

array([0.06708846, 0.07141926, 0.24761339, 0.64343346, 0.98412292])

# 7 . randn() ==> This function is used to generate a random number from -3 to close 3 . This may return positive or negative numbers as well .

# syntax == random.randn(number of values)

In [ ]:
import numpy as np
a = np.random.randn(5)
a

array([-0.83676406, -0.64319371,  1.93291174,  0.85973616, -0.26271558])

# Reshaping Data

In [ ]:
import numpy as np

a = np.random.randint(1,50,12)

a

array([36, 23, 31, 30,  9, 29, 41, 13, 11, 23, 13, 45])

In [ ]:
a.shape

(12,)

In [ ]:
a = a.reshape(2,6)
a

array([[36, 23, 31, 30,  9, 29],
       [41, 13, 11, 23, 13, 45]])

In [ ]:
a = a.reshape(6,2)
a

array([[36, 23],
       [31, 30],
       [ 9, 29],
       [41, 13],
       [11, 23],
       [13, 45]])

In [ ]:
a = a.reshape(3,4)
a

array([[36, 23, 31, 30],
       [ 9, 29, 41, 13],
       [11, 23, 13, 45]])

In [ ]:
a = a.reshape(4,3)
a

array([[36, 23, 31],
       [30,  9, 29],
       [41, 13, 11],
       [23, 13, 45]])

In [ ]:
a = a.reshape(12,1)
a

array([[36],
       [23],
       [31],
       [30],
       [ 9],
       [29],
       [41],
       [13],
       [11],
       [23],
       [13],
       [45]])

# principal of -1

In [ ]:
a = a.reshape(-1 , 4)
a

array([[36, 23, 31, 30],
       [ 9, 29, 41, 13],
       [11, 23, 13, 45]])

# Seed Function ()  ==> We know that randint function generates random numbers . Everytime we run the program  , new set of random number is generated . So , solve this problem we will use seed function .

In [ ]:
import numpy as np

np.random.seed(12)
a = np.random.randint(1,100 , 10)
a

array([76, 28,  7,  3,  4, 68, 77, 49, 23, 50])

#### np.random.seed(111)
a = np.random.randint(1,500,30).reshape(6,5)
a

# View Vs Copy ==> When we slice a sub-array from an array , it may be done by two ways .

In [ ]:
import numpy as np
a = np.array([10 , 20 , 30 , 40 , 50 , 60 , 70 , 80 ])
b = a[3:6]
b[:] = 0
a

array([10, 20, 30,  0,  0,  0, 70, 80])

# copy

In [ ]:
a = np.array([10 , 20 , 30 , 40 , 50 , 60 , 70 , 80 ])
b = a[3:6].copy()
b[:] = 0
a

array([10, 20, 30, 40, 50, 60, 70, 80])

In [ ]:
b

array([0, 0, 0])

# conditional selection

In [ ]:
import numpy as np
a = np.arange(1,16)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [ ]:
a<10

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False])

In [ ]:
b = a>10
a[b]

array([11, 12, 13, 14, 15])

In [ ]:
a[a%2 == 0]

array([ 2,  4,  6,  8, 10, 12, 14])

# Operations on Array

In [ ]:
import numpy as np
a = np.arange(1,5)
a*2

array([2, 4, 6, 8])

In [ ]:
a+2

array([3, 4, 5, 6])

In [ ]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [ ]:
a  = np.array([1,2,3,4]).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [ ]:
b = np.array([5,6,7,8]).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [ ]:
a+b

array([[ 6,  8],
       [10, 12]])

In [ ]:
b-a

array([[4, 4],
       [4, 4]])

In [ ]:
b/a

array([[5.        , 3.        ],
       [2.33333333, 2.        ]])

In [ ]:
a*b

array([[ 5, 12],
       [21, 32]])

In [ ]:
a.dot(b)

array([[19, 22],
       [43, 50]])

# some more important numpy functions

In [ ]:
import  numpy as np
a = np.array([10,20,30,40,50])
np.min(a)

10

In [ ]:
np.max(a)

50

In [ ]:
np.argmin(a)

0

In [ ]:
np.argmax(a)

4

In [ ]:
np.sqrt(a)

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781])

In [ ]:
np.sin(a)

array([-0.54402111,  0.91294525, -0.98803162,  0.74511316, -0.26237485])

# Linspace() ==> This function returns value between a given range and with a same gap between consicutive elements .

In [ ]:
import numpy as np

a = np.linspace(1,2,5)
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [ ]:
import numpy as np

np.random.seed(122)
a = np.random.randint(1,21,9).reshape(3,3)
a

array([[16, 11, 13],
       [17, 13, 16],
       [ 3, 16, 11]])

In [ ]:
np.sum(a)

116

In [ ]:
np.sum(a , axis = 1)

array([40, 46, 30])

In [ ]:
np.min(a)

3

In [ ]:
np.max(a)

17

In [ ]:
np.cumsum(a)

array([ 16,  27,  40,  57,  70,  86,  89, 105, 116], dtype=int32)

In [ ]:
a

array([[16, 11, 13],
       [17, 13, 16],
       [ 3, 16, 11]])

# np.unique(arr , return_index = True , return_counts = True)

returns 3 array .
1 . the array with unique values .
2 . the array with respective index value .
3 . the array with counting of frequencey .

In [ ]:
a = np.array([10,20,30,40,10,20,50])
np.unique(a , return_index  = True , return_counts = True)


(array([10, 20, 30, 40, 50]),
 array([0, 1, 2, 3, 6], dtype=int64),
 array([2, 2, 1, 1, 1], dtype=int64))

# horizontal and vertical stacking

In [ ]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
a

array([1, 2, 3, 4])

In [ ]:
b

array([5, 6, 7, 8])

In [ ]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

# Q.1 = Write statement to import numpy ?

Q.2 = Create an array using numpy ?

Q.3 = Create an array of 10 random integers ?

Q.4 = Create an array of elements from  10-20?

Q.5 = Create an array which contains value 5 , 10 times ?

Q.6 = Create a one dimensional array and convert that into 3*3 matrix ?

Q.7 = Create a 2D array of size 3*3 but all the elements should be between 0 to 1 ?

Q.8 = Concatenate 2D array horizontally and vertically ?