In [1]:
import numpy as np

In [2]:
a = [1,45,90]
b = np.array(a)
b

array([ 1, 45, 90])

In [3]:
print("total dimension:", b.ndim)
print("shape of the array", b.shape)
print("total elements",b.size)

total dimension: 1
shape of the array (3,)
total elements 3


In [4]:
 # it will create an array in which all numbers are zero
 a = np.zeros(5)
 a

array([0., 0., 0., 0., 0.])

In [5]:
b = np.zeros((2,3))
b


array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
# ones  function ===> it will create an array either in dimentional or two dimentional
a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [8]:
b = np.ones((2,3))
b

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
# Eye method - all digonal element will be one
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
# diagonal function
# syntax - diag
a = np.diag([1,4,8,9])
a

array([[1, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 8, 0],
       [0, 0, 0, 9]])

In [14]:
# random integer function
# randint(min_value,max_value_total_number)
a = np.random.randint(1,20,3)
a

array([10,  2,  7])

In [15]:
# randn() function:- this function is used to generate a random number from -3 to 3


In [16]:
#Reshaping data
a = np.random.randint(1,50,12)
a

array([36, 15, 34,  1, 14, 35, 18, 35, 11,  2, 49, 43])

In [17]:
a.shape

(12,)

In [19]:
a = a.reshape(2,6)
a

array([[36, 15, 34,  1, 14, 35],
       [18, 35, 11,  2, 49, 43]])

In [20]:
a = a.reshape(6,2)
a

array([[36, 15],
       [34,  1],
       [14, 35],
       [18, 35],
       [11,  2],
       [49, 43]])

**Principal of -1**

In [21]:
a = a.reshape(-1,4)
a

array([[36, 15, 34,  1],
       [14, 35, 18, 35],
       [11,  2, 49, 43]])

**Seed Function**

In [23]:
np.random.seed(5)
a = np.random.randint(1,100,10)
a

array([79, 62, 17, 74,  9, 63, 28, 31, 81,  8])

**View as copy**

In [24]:
a = np.array([10,20,30,40,50,60,70,80])
b = a[3:6]
b

array([40, 50, 60])

In [29]:
a = np.array([10,20,30,40,50,60,70,80])
b = a[3:6].copy()
b[:] = 0
b


array([0, 0, 0])

**Conditional Selection**

In [30]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
a>7


array([False, False, False, False, False, False, False,  True,  True])

In [32]:
b = a>10
a[b]

array([], dtype=int64)

**Operation on Array**

In [34]:
a = np.arange(1,5)
a*2

array([2, 4, 6, 8])

In [35]:
a+2

array([3, 4, 5, 6])

In [36]:
a**2


array([ 1,  4,  9, 16])

In [37]:
a = np.array([1,2,3,4]).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [38]:
b = np.array([5,6,7,8]).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [39]:
a+b

array([[ 6,  8],
       [10, 12]])

In [40]:
b-a


array([[4, 4],
       [4, 4]])

In [41]:
b/a

array([[5.        , 3.        ],
       [2.33333333, 2.        ]])

In [42]:
a.dot(b)

array([[19, 22],
       [43, 50]])

In [43]:
a  = np.array([10,20,30,40,50,60])
np.min(a)

10

In [44]:
np.max(a)

60

In [45]:
np.argmin(a)

0

In [46]:
np.argmax(a)

5

In [47]:
np.sqrt(a)


array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781,
       7.74596669])

In [48]:
np.sin(a)

array([-0.54402111,  0.91294525, -0.98803162,  0.74511316, -0.26237485,
       -0.30481062])

**Linspace() Function**

In [49]:
a = np.linspace(1,2,5)
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [50]:
np.sum


<function sum at 0x78cf0633c6b0>

In [51]:
#np.sum
#np.sum(a, axis = 1)

**np.unique(arr,return_index = true, return counts = true)**

In [52]:
a = np.array([10,20,30,40,10,20,50])
np.unique(a, return_index = True, return_counts = True)

(array([10, 20, 30, 40, 50]), array([0, 1, 2, 3, 6]), array([2, 2, 1, 1, 1]))

**Horizontal and Vertical Stacking**

In [53]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [55]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [56]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])